window.hskData = [
    { "id": 1, "word": "爱", "pinyin": "ài", "meaning": "yêu, thích", "example": "我爱你 (Wǒ ài nǐ) - Tôi yêu bạn", "tip": "Có bộ Tâm (心 - trái tim) ở giữa. Tình yêu xuất phát từ trái tim." },
    { "id": 2, "word": "八", "pinyin": "bā", "meaning": "số 8", "example": "八个人 (Bā gè rén) - 8 người", "tip": "Hình dáng giống như hai ria mép bẻ cong ra hai bên." },
    { "id": 3, "word": "爸爸", "pinyin": "bàba", "meaning": "bố, cha", "example": "我爸爸是医生 (Wǒ bàba shì yīshēng) - Bố tôi là bác sĩ", "tip": "Gồm bộ Phụ (父 - người cha) ở trên và chữ Ba (巴) mượn âm ở dưới." },
    { "id": 4, "word": "杯子", "pinyin": "bēizi", "meaning": "cái cốc", "example": "一个杯子 (Yí gè bēizi) - Một cái cốc", "tip": "Có bộ Mộc (木 - gỗ) ở bên trái, vì ngày xưa cốc thường được làm bằng gỗ." },
    { "id": 5, "word": "北京", "pinyin": "Běijīng", "meaning": "Bắc Kinh", "example": "我去北京 (Wǒ qù Běijīng) - Tôi đi Bắc Kinh", "tip": "Bắc (北) Kinh (京) - Thủ đô ở phía Bắc Trung Quốc." },
    { "id": 6, "word": "本", "pinyin": "běn", "meaning": "quyển, cuốn (lượng từ)", "example": "一本书 (Yì běn shū) - Một quyển sách", "isMeasureWord": true, "tip": "Chữ Mộc (木) được gạch ngang ở dưới gốc, ý chỉ 'gốc rễ'. Sách là gốc rễ của tri thức." },
    { "id": 7, "word": "不客气", "pinyin": "bú kèqi", "meaning": "không có gì", "example": "谢谢！- 不客气 (Xièxie! - Bú kèqi) - Cảm ơn! - Không có gì", "tip": "Khách khí (客气) nghĩa là sáo rỗng, khách sáo. Bú kèqi là đừng khách sáo." },
    { "id": 8, "word": "不", "pinyin": "bù", "meaning": "không", "example": "我不是老师 (Wǒ bú shì lǎoshī) - Tôi không phải là giáo viên", "tip": "Giống hình một rễ cây cắm xuống đất, mang ý nghĩa phủ định sự phát triển lên trên." },
    { "id": 9, "word": "菜", "pinyin": "cài", "meaning": "rau, món ăn", "example": "中国菜很好吃 (Zhōngguó cài hěn hǎochī) - Món ăn Trung Quốc rất ngon", "tip": "Có bộ Thảo (艹 - cỏ, cây) ở trên, chỉ các loại thực vật, rau xanh." },
    { "id": 10, "word": "茶", "pinyin": "chá", "meaning": "trà", "example": "喝茶 (Hē chá) - Uống trà", "tip": "Có bộ Thảo (艹) ở trên cùng, vì trà là một loại lá cây (thực vật)." },
    { "id": 11, "word": "吃", "pinyin": "chī", "meaning": "ăn", "example": "吃饭 (Chī fàn) - Ăn cơm", "tip": "Bộ Khẩu (口 - miệng) ở bên trái, vì ăn thì phải dùng miệng." },
    { "id": 12, "word": "出租车", "pinyin": "chūzūchē", "meaning": "xe taxi", "example": "坐出租车 (Zuò chūzūchē) - Đi taxi", "tip": "Xuất tô xa: Xe (车) được đem ra (出) để cho thuê (租)." },
    { "id": 13, "word": "打电话", "pinyin": "dǎ diànhuà", "meaning": "gọi điện thoại", "example": "他在打电话 (Tā zài dǎ diànhuà) - Anh ấy đang gọi điện", "tip": "Chữ Đả (打) có bộ Thủ (tay), vì gọi điện thoại phải dùng tay cầm máy." },
    { "id": 14, "word": "大", "pinyin": "dà", "meaning": "to, lớn", "example": "这个苹果很大 (Zhège píngguǒ hěn dà) - Quả táo này rất to", "tip": "Hình một người dang rộng hai tay hai chân để thể hiện sự to lớn." },
    { "id": 15, "word": "的", "pinyin": "de", "meaning": "của (trợ từ)", "example": "我的书 (Wǒ de shū) - Sách của tôi", "tip": "Bên trái là Bạch (白 - trắng), bên phải là Bao (勺 - cái thìa)." },
    { "id": 16, "word": "点", "pinyin": "diǎn", "meaning": "giờ, chút xíu (lượng từ)", "example": "现在八点 (Xiànzài bā diǎn) - Bây giờ là 8 giờ", "isMeasureWord": true, "tip": "Có 4 chấm Hỏa (灬) ở dưới, tượng trưng cho bếp lửa đang đun đun dần từng chút một." },
    { "id": 17, "word": "电脑", "pinyin": "diànnǎo", "meaning": "máy tính", "example": "我的电脑 (Wǒ de diànnǎo) - Máy tính của tôi", "tip": "Điện (电) Não (脑): Một bộ não chạy bằng điện tử." },
    { "id": 18, "word": "电视", "pinyin": "diànshì", "meaning": "tivi", "example": "看电视 (Kàn diànshì) - Xem tivi", "tip": "Điện (电) Thị (视): Nhìn (thị) hình ảnh qua tín hiệu điện." },
    { "id": 19, "word": "电影", "pinyin": "diànyǐng", "meaning": "phim", "example": "看电影 (Kàn diànyǐng) - Xem phim", "tip": "Điện (电) Ảnh (影): Những bóng ảnh chuyển động bằng điện." },
    { "id": 20, "word": "东西", "pinyin": "dōngxi", "meaning": "đồ vật, thứ", "example": "买东西 (Mǎi dōngxi) - Mua đồ", "tip": "Đông (东) Tây (西): Chỉ mọi thứ trên đời từ phương Đông sang phương Tây." },
    { "id": 21, "word": "都", "pinyin": "dōu", "meaning": "đều", "example": "我们都是学生 (Wǒmen dōu shì xuéshēng) - Chúng tôi đều là học sinh", "tip": "Bao gồm chữ Giả (者 - người) và bộ ấp (阝- vùng đất). Mọi người trong một vùng ĐỀU giống nhau." },
    { "id": 22, "word": "读", "pinyin": "dú", "meaning": "đọc", "example": "读书 (Dú shū) - Đọc sách", "tip": "Có bộ Ngôn (讠) bên trái, liên quan đến lời nói, đọc thành tiếng." },
    { "id": 23, "word": "对不起", "pinyin": "duìbuqǐ", "meaning": "xin lỗi", "example": "对不起，我迟到了 (Duìbuqǐ, wǒ chídào le) - Xin lỗi, tôi đến muộn", "tip": "Nghĩa đen là 'Đối không nổi', cảm thấy áy náy không dám đối mặt." },
    { "id": 24, "word": "多", "pinyin": "duō", "meaning": "nhiều", "example": "很多人 (Hěn duō rén) - Rất nhiều người", "tip": "Gồm hai chữ Tịch (夕 - buổi tối) chồng lên nhau. Nhiều đêm trôi qua -> Nhiều." },
    { "id": 25, "word": "多少", "pinyin": "duōshao", "meaning": "bao nhiêu", "example": "多少钱？(Duōshao qián?) - Bao nhiêu tiền?", "tip": "Ghép từ Đa (多 - nhiều) và Thiểu (少 - ít), dùng để hỏi số lượng lớn." },
    { "id": 26, "word": "儿子", "pinyin": "érzi", "meaning": "con trai", "example": "我的儿子 (Wǒ de érzi) - Con trai tôi", "tip": "Nhi (儿) - Hình ảnh đứa trẻ đang chạy nhảy." },
    { "id": 27, "word": "二", "pinyin": "èr", "meaning": "số 2", "example": "两个 (Liǎng gè) - Hai cái (dùng 两 thay 二)", "tip": "Hai gạch ngang đơn giản tượng trưng cho số 2." },
    { "id": 28, "word": "饭馆", "pinyin": "fànguǎn", "meaning": "quán ăn, nhà hàng", "example": "去饭馆吃饭 (Qù fànguǎn chī fàn) - Đi quán ăn", "tip": "Chữ Phạn (饭) có bộ Thực (饣- đồ ăn), Quán (馆) là nơi chốn." },
    { "id": 29, "word": "飞机", "pinyin": "fēijī", "meaning": "máy bay", "example": "坐飞机 (Zuò fēijī) - Ngồi máy bay", "tip": "Phi (飞 - bay) và Cơ (机 - máy móc). Cỗ máy biết bay." },
    { "id": 30, "word": "分钟", "pinyin": "fēnzhōng", "meaning": "phút (lượng từ)", "example": "五分钟 (Wǔ fēnzhōng) - 5 phút", "isMeasureWord": true, "tip": "Phân (分 - chia nhỏ), Chung (钟 - đồng hồ). Chia nhỏ thời gian đồng hồ là phút." },
    { "id": 31, "word": "高兴", "pinyin": "gāoxìng", "meaning": "vui vẻ", "example": "很高兴认识你 (Hěn gāoxìng rènshi nǐ) - Rất vui được quen bạn", "tip": "Cao Hứng. Cao (高 - cao), Hứng (兴 - hào hứng). Tinh thần lên cao." },
    { "id": 32, "word": "个", "pinyin": "gè", "meaning": "cái, con (lượng từ)", "example": "一个人 (Yí gè rén) - Một người", "isMeasureWord": true, "tip": "Hình dáng giống như một người đang đứng dang chân, là lượng từ phổ biến nhất." },
    { "id": 33, "word": "工作", "pinyin": "gōngzuò", "meaning": "công việc, làm việc", "example": "他在医院工作 (Tā zài yīyuàn gōngzuò) - Anh ấy làm ở bệnh viện", "tip": "Công (工 - công nhân, công việc). Hình cái đe thợ rèn." },
    { "id": 34, "word": "汉语", "pinyin": "Hànyǔ", "meaning": "tiếng Hán, tiếng Trung", "example": "学习汉语 (Xuéxí Hànyǔ) - Học tiếng Trung", "tip": "Ngữ (语) có bộ Ngôn (讠) chỉ ngôn ngữ, lời nói." },
    { "id": 35, "word": "好", "pinyin": "hǎo", "meaning": "tốt, khỏe, hay", "example": "你好 (Nǐ hǎo) - Xin chào", "tip": "Bên trái là Nữ (女), phải là Tử (子 - con trai). Phụ nữ có con trai nối dõi là điều 'Tốt' theo quan niệm xưa." },
    { "id": 36, "word": "号", "pinyin": "hào", "meaning": "ngày, số", "example": "今天几号？(Jīntiān jǐ hào?) - Hôm nay ngày mấy?", "tip": "Chữ Khẩu (口) ở trên, chữ mã (tượng hình số liệu) ở dưới." },
    { "id": 37, "word": "喝", "pinyin": "hē", "meaning": "uống", "example": "喝水 (Hē shuǐ) - Uống nước", "tip": "Có bộ Khẩu (口 - miệng) vì uống thì phải dùng miệng." },
    { "id": 38, "word": "和", "pinyin": "hé", "meaning": "và", "example": "我和你 (Wǒ hé nǐ) - Tôi và bạn", "tip": "Bộ Hòa (禾 - cây lúa) và bộ Khẩu (口). Mọi người cùng ăn cơm chung hòa thuận (và)." },
    { "id": 39, "word": "很", "pinyin": "hěn", "meaning": "rất", "example": "很好 (Hěn hǎo) - Rất tốt", "tip": "Bộ Xích (彳- bước ngắn) chỉ mức độ tăng tiến dần lên." },
    { "id": 40, "word": "后面", "pinyin": "hòumiàn", "meaning": "phía sau", "example": "在后面 (Zài hòumiàn) - Ở phía sau", "tip": "Hậu (后 - phía sau) Diện (面 - mặt)." },
    { "id": 41, "word": "回", "pinyin": "huí", "meaning": "về", "example": "回家 (Huí jiā) - Về nhà", "tip": "Hình ảnh vòng xoáy ốc, đi ra rồi lại vòng về trung tâm (nhà)." },
    { "id": 42, "word": "会", "pinyin": "huì", "meaning": "biết (kỹ năng), sẽ", "example": "我会说汉语 (Wǒ huì shuō Hànyǔ) - Tôi biết nói tiếng Trung", "tip": "Trên là bộ Nhân (人), hội tụ lại học hỏi thì sẽ 'biết' làm." },
    { "id": 43, "word": "几", "pinyin": "jǐ", "meaning": "mấy (hỏi số lượng < 10)", "example": "几个人？(Jǐ gè rén?) - Mấy người?", "tip": "Giống cái bàn nhỏ, thường dùng để đếm các vật số lượng ít đẻ trên bàn." },
    { "id": 44, "word": "家", "pinyin": "jiā", "meaning": "nhà, gia đình", "example": "我家有四口人 (Wǒ jiā yǒu sì kǒu rén) - Nhà tôi có 4 người", "tip": "Dưới bộ Miên (宀 - mái nhà) có chữ Thỉ (豕 - con lợn). Ngày xưa nhà nào có nuôi lợn dưới mái che thì đó là 'nhà'." },
    { "id": 45, "word": "叫", "pinyin": "jiào", "meaning": "gọi, tên là", "example": "我叫玛丽 (Wǒ jiào Mǎlì) - Tôi tên là Mary", "tip": "Bộ Khẩu (口 - miệng) dùng để gọi tên." },
    { "id": 46, "word": "今天", "pinyin": "jīntiān", "meaning": "hôm nay", "example": "今天天气很好 (Jīntiān tiānqì hěn hǎo) - Hôm nay thời tiết tốt", "tip": "Kim (今 - hiện tại) Thiên (天 - ngày, trời). Ngày hiện tại." },
    { "id": 47, "word": "九", "pinyin": "jiǔ", "meaning": "số 9", "example": "九个月 (Jiǔ gè yuè) - 9 tháng", "tip": "Trông giống hình móc câu hoặc con rồng uốn lượn (cửu long)." },
    { "id": 48, "word": "开", "pinyin": "kāi", "meaning": "mở, lái", "example": "开门 (Kāi mén) - Mở cửa", "tip": "Hình ảnh hai tay đẩy cánh cửa mở rộng ra hai bên." },
    { "id": 49, "word": "看", "pinyin": "kàn", "meaning": "nhìn, xem", "example": "看书 (Kàn shū) - Đọc sách", "tip": "Bộ Thủ (tay) đưa lên che trên bộ Mục (mắt) để nhìn cho rõ." },
    { "id": 50, "word": "看见", "pinyin": "kànjiàn", "meaning": "nhìn thấy", "example": "我看见他了 (Wǒ kànjiàn tā le) - Tôi nhìn thấy anh ấy", "tip": "Khán (看 - nhìn) Kiến (见 - thấy)." },
    { "id": 51, "word": "块", "pinyin": "kuài", "meaning": "đồng, cục, hòn (lượng từ)", "example": "十块钱 (Shí kuài qián) - 10 đồng", "isMeasureWord": true, "tip": "Có bộ Thổ (土 - đất) bên trái, vì cục/hòn thường làm từ đất cát." },
    { "id": 52, "word": "来", "pinyin": "lái", "meaning": "đến", "example": "他来了 (Tā lái le) - Anh ấy đến rồi", "tip": "Giống hình cây lúa. Người xưa hay bảo 'đến' mùa gặt lúa." },
    { "id": 53, "word": "老师", "pinyin": "lǎoshī", "meaning": "giáo viên", "example": "他是我的老师 (Tā shì wǒ lǎoshī) - Ông ấy là giáo viên của tôi", "tip": "Lão (老 - người lớn tuổi, kinh nghiệm) Sư (师 - thầy)." },
    { "id": 54, "word": "了", "pinyin": "le", "meaning": "rồi (trợ từ)", "example": "下雨了 (Xiàyǔ le) - Trời mưa rồi", "tip": "Hình ảnh đứa bé đã mọc tóc, mọi thứ đã hoàn thành (xong rồi)." },
    { "id": 55, "word": "冷", "pinyin": "lěng", "meaning": "lạnh", "example": "今天很冷 (Jīntiān hěn lěng) - Hôm nay rất lạnh", "tip": "Có bộ Băng (冫- hai chấm băng) bên trái, liên quan đến sự lạnh buốt." },
    { "id": 56, "word": "里", "pinyin": "lǐ", "meaning": "trong", "example": "在家里 (Zài jiā lǐ) - Ở trong nhà", "tip": "Chữ Nhật (mặt trời) và chữ Thổ (đất). Trong lòng đất." },
    { "id": 57, "word": "零", "pinyin": "líng", "meaning": "số 0", "example": "二零二四年 (Èr líng èr sì nián) - Năm 2024", "tip": "Có bộ Vũ (mưa) ở trên, những giọt mưa rơi lác đác rải rác (linh tinh -> số 0)." },
    { "id": 58, "word": "六", "pinyin": "liù", "meaning": "số 6", "example": "六天 (Liù tiān) - 6 ngày", "tip": "Trông giống hình một người đang dang hai chân đứng vững vàng." },
    { "id": 59, "word": "妈妈", "pinyin": "māma", "meaning": "mẹ", "example": "我爱我妈妈 (Wǒ ài wǒ māma) - Tôi yêu mẹ", "tip": "Bộ Nữ (女 - phụ nữ) và chữ Mã (马 - con ngựa). Người phụ nữ làm việc cực nhọc như ngựa vì con." },
    { "id": 60, "word": "吗", "pinyin": "ma", "meaning": "không? (trợ từ)", "example": "你好吗？(Nǐ hǎo ma?) - Bạn khỏe không?", "tip": "Có bộ Khẩu (口 - miệng) vì dùng miệng để hỏi." },
    { "id": 61, "word": "买", "pinyin": "mǎi", "meaning": "mua", "example": "买苹果 (Mǎi píngguǒ) - Mua táo", "tip": "Chữ Mãi: Đội nón đi mua đồ (không có chữ thập bên trên như chữ Bán/Bán đi)." },
    { "id": 62, "word": "猫", "pinyin": "māo", "meaning": "con mèo", "example": "我的小猫 (Wǒ de xiǎo māo) - Con mèo nhỏ", "tip": "Bộ Khuyển (犭- động vật) và chữ Miêu (苗 - mầm cây, mượn âm)." },
    { "id": 63, "word": "没", "pinyin": "méi", "meaning": "không, chưa", "example": "我没去 (Wǒ méi qù) - Tôi chưa đi", "tip": "Có bộ Thủy (氵). Hình ảnh tay cầm cây ném xuống nước chìm nghỉm -> Mất tích, không còn." },
    { "id": 64, "word": "没关系", "pinyin": "méi guānxi", "meaning": "không sao", "example": "对不起！- 没关系 (Duìbuqǐ! - Méi guānxi)", "tip": "Chẳng (没) liên quan (关系)." },
    { "id": 65, "word": "明天", "pinyin": "míngtiān", "meaning": "ngày mai", "example": "明天见 (Míngtiān jiàn) - Ngày mai gặp", "tip": "Minh (明) gồm Nhật (Mặt trời) và Nguyệt (Mặt trăng), trôi qua ngày và đêm là tới ngày mai." },
    { "id": 66, "word": "名字", "pinyin": "míngzi", "meaning": "tên", "example": "你叫什么名字？(Nǐ jiào shénme míngzi?)", "tip": "Danh (名) Tự (字). Danh có bộ Tịch (buổi tối) và Khẩu (miệng). Buổi tối tối thui phải dùng miệng gọi Tên để nhận ra nhau." },
    { "id": 67, "word": "哪", "pinyin": "nǎ", "meaning": "nào", "example": "你是哪国人？(Nǐ shì nǎ guó rén?) - Bạn người nước nào?", "tip": "Thêm bộ Khẩu (口) đằng trước chữ Na (kia) để tạo thành câu hỏi 'Nào?'." },
    { "id": 68, "word": "哪儿", "pinyin": "nǎ'er", "meaning": "ở đâu", "example": "你去哪儿？(Nǐ qù nǎ'er?) - Đi đâu?", "tip": "Thêm chữ Nhi (儿) để chỉ địa điểm chốn." },
    { "id": 69, "word": "那", "pinyin": "nà", "meaning": "kia, đó", "example": "那是我的书 (Nà shì wǒ de shū)", "tip": "Có bộ ấp (阝- vùng đất), chỉ một vùng đất ở phía 'đằng kia'." },
    { "id": 70, "word": "呢", "pinyin": "ne", "meaning": "nhỉ, thế", "example": "你呢？(Nǐ ne?) - Còn bạn?", "tip": "Có bộ Khẩu (口) dùng để hỏi ngược lại." },
    { "id": 71, "word": "能", "pinyin": "néng", "meaning": "có thể", "example": "我能进来吗？(Wǒ néng jìnlái ma?)", "tip": "Hình ảnh một con gấu to lớn (hùng), móng vuốt sắc nhọn -> Có Năng lực làm được mọi việc." },
    { "id": 72, "word": "你", "pinyin": "nǐ", "meaning": "bạn", "example": "谢谢你 (Xièxie nǐ)", "tip": "Bộ Nhân đứng (亻- người). Ngươi, bạn." },
    { "id": 73, "word": "年", "pinyin": "nián", "meaning": "năm", "example": "今年 (Jīnnián) - Năm nay", "tip": "Hình ảnh bó lúa mọc trên cánh đồng. Mỗi năm thu hoạch lúa một lần." },
    { "id": 74, "word": "女儿", "pinyin": "nǚ'ér", "meaning": "con gái", "example": "她是我女儿 (Tā shì wǒ nǚ'ér)", "tip": "Nữ (女 - đàn bà, con gái) Nhi (儿 - trẻ con)." },
    { "id": 75, "word": "朋友", "pinyin": "péngyou", "meaning": "bạn bè", "example": "好朋友 (Hǎo péngyou)", "tip": "Bằng Hữu. Chữ Bằng (朋) gồm hai chữ Nguyệt (Mặt trăng) đứng cạnh nhau -> Những người giống nhau chơi chung." },
    { "id": 76, "word": "漂亮", "pinyin": "piàoliang", "meaning": "xinh đẹp", "example": "她很漂亮 (Tā hěn piàoliang)", "tip": "Phiêu (漂) Lượng (亮 - sáng). Đẹp tỏa sáng." },
    { "id": 77, "word": "苹果", "pinyin": "píngguǒ", "meaning": "quả táo", "example": "吃苹果 (Chī píngguǒ)", "tip": "Quả (果) có bộ Mộc (cây), trái cây nói chung. Bình (苹) là loại cây." },
    { "id": 78, "word": "七", "pinyin": "qī", "meaning": "số 7", "example": "七点 (Qī diǎn) - 7 giờ", "tip": "Gạch ngang và nét sổ cong giống hình một con dao găm (giới số 7 xưa)." },
    { "id": 79, "word": "钱", "pinyin": "qián", "meaning": "tiền", "example": "多少钱？(Duōshao qián?)", "tip": "Bộ Kim (钅- kim loại) bên trái, vì tiền cổ làm bằng đồng, vàng." },
    { "id": 80, "word": "前面", "pinyin": "qiánmiàn", "meaning": "phía trước", "example": "在前面 (Zài qiánmiàn)", "tip": "Tiền (前 - trước), Diện (面 - mặt)." },
    { "id": 81, "word": "请", "pinyin": "qǐng", "meaning": "mời, xin", "example": "请坐 (Qǐng zuò) - Mời ngồi", "tip": "Có bộ Ngôn (讠) bên trái. Muốn mời ai phải dùng Lời nói đàng hoàng." },
    { "id": 82, "word": "去", "pinyin": "qù", "meaning": "đi", "example": "去学校 (Qù xuéxiào)", "tip": "Hình người đang bước đi dang rộng chân khỏi một cái nắp." },
    { "id": 83, "word": "热", "pinyin": "rè", "meaning": "nóng", "example": "今天很热 (Jīntiān hěn rè)", "tip": "Có 4 chấm Hỏa (灬) ở dưới, tượng trưng cho lửa đốt rất nóng." },
    { "id": 84, "word": "人", "pinyin": "rén", "meaning": "người", "example": "中国人 (Zhōngguó rén)", "tip": "Hình người đang bước đi bằng hai chân." },
    { "id": 85, "word": "认识", "pinyin": "rènshi", "meaning": "quen biết", "example": "认识你很高兴 (Rènshi nǐ hěn gāoxìng)", "tip": "Nhận Thức. Cả 2 chữ đều có bộ Ngôn (讠). Quen biết nhau qua lời nói, trò chuyện." },
    { "id": 86, "word": "三", "pinyin": "sān", "meaning": "số 3", "example": "三个月 (Sān gè yuè)", "tip": "Ba vạch ngang đơn giản đại diện cho số 3." },
    { "id": 87, "word": "商店", "pinyin": "shāngdiàn", "meaning": "cửa hàng", "example": "去商店 (Qù shāngdiàn)", "tip": "Thương (商 - buôn bán) Điếm (店 - tiệm)." },
    { "id": 88, "word": "上", "pinyin": "shàng", "meaning": "trên, lên", "example": "桌子上 (Zhuōzi shàng) - Trên bàn", "tip": "Mũi tên chỉ hướng lên trên đường gạch ngang." },
    { "id": 89, "word": "上午", "pinyin": "shàngwǔ", "meaning": "buổi sáng", "example": "今天上午 (Jīntiān shàngwǔ)", "tip": "Thượng Ngọ. Nửa buổi (thượng) trước giờ Ngọ (12h trưa)." },
    { "id": 90, "word": "少", "pinyin": "shǎo", "meaning": "ít", "example": "很少 (Hěn shǎo)", "tip": "Chữ Tiểu (小 - nhỏ) bị gạch bớt một nét ở dưới -> Nhỏ mà còn bị bớt đi nên rất ÍT." },
    { "id": 91, "word": "谁", "pinyin": "shéi", "meaning": "ai", "example": "他是谁？(Tā shì shéi?)", "tip": "Bộ Ngôn (讠) bên trái. Dùng lời nói để hỏi xem người kia là Ai." },
    { "id": 92, "word": "什么", "pinyin": "shénme", "meaning": "cái gì", "example": "这是什么？(Zhè shì shénme?)", "tip": "Thập Ma. Đại từ nghi vấn thường gặp." },
    { "id": 93, "word": "十", "pinyin": "shí", "meaning": "số 10", "example": "十个人 (Shí gè rén)", "tip": "Hình chữ thập, hai nét chéo giao nhau thể hiện sự đầy đủ (10 là tròn chục)." },
    { "id": 94, "word": "时候", "pinyin": "shíhou", "meaning": "lúc, khi", "example": "什么时候？(Shénme shíhou?)", "tip": "Thời Hậu. Thời (时) có bộ Nhật (ngày, thời gian)." },
    { "id": 95, "word": "是", "pinyin": "shì", "meaning": "là", "example": "我是学生 (Wǒ shì xuéshēng)", "tip": "Có chữ Nhật (ngày) và chữ Chính (ngay thẳng) bên dưới. Điều đúng đắn, chân lý." },
    { "id": 96, "word": "书", "pinyin": "shū", "meaning": "sách", "example": "一本书 (Yì běn shū)", "tip": "Hình ảnh cây bút đang gạch những nét chữ vào trang giấy." },
    { "id": 97, "word": "水", "pinyin": "shuǐ", "meaning": "nước", "example": "喝水 (Hē shuǐ)", "tip": "Hình ảnh dòng suối chảy ngoằn ngoèo giữa các vách đá." },
    { "id": 98, "word": "水果", "pinyin": "shuǐguǒ", "meaning": "hoa quả", "example": "买水果 (Mǎi shuǐguǒ)", "tip": "Thủy (nước) Quả (trái). Trái cây chứa rất nhiều nước." },
    { "id": 99, "word": "睡觉", "pinyin": "shuìjiào", "meaning": "ngủ", "example": "我要睡觉了 (Wǒ yào shuìjiào le)", "tip": "Chữ Thụy (睡) có bộ Mục (mắt) và chữ Thùy (rủ xuống). Mắt rủ cụp xuống là lúc buồn ngủ." },
    { "id": 100, "word": "说话", "pinyin": "shuōhuà", "meaning": "nói chuyện", "example": "他在说话 (Tā zài shuōhuà)", "tip": "Thuyết Thoại. Cả 2 chữ đều có bộ Ngôn (讠) chỉ lời nói." },
    { "id": 101, "word": "四", "pinyin": "sì", "meaning": "số 4", "example": "四本书 (Sì běn shū)", "tip": "Khung vuông nhốt hai nét phẩy, phát âm gần giống chữ Tử (chết) nên bị coi là số xui." },
    { "id": 102, "word": "岁", "pinyin": "suì", "meaning": "tuổi (lượng từ tuổi tác)", "example": "我二十岁 (Wǒ èrshí suì)", "isMeasureWord": true, "tip": "Bộ Sơn (núi) ở trên, chữ Tịch (tối) ở dưới. Một năm trôi qua như ngọn núi đổ bóng chiều." },
    { "id": 103, "word": "他", "pinyin": "tā", "meaning": "anh ấy, ông ấy", "example": "他是我的朋友 (Tā shì wǒ de péngyou)", "tip": "Có bộ Nhân đứng (亻) để chỉ người phái nam." },
    { "id": 104, "word": "她", "pinyin": "tā", "meaning": "cô ấy, bà ấy", "example": "她很漂亮 (Tā hěn piàoliang)", "tip": "Có bộ Nữ (女) bên trái để phân biệt là phụ nữ." },
    { "id": 105, "word": "太", "pinyin": "tài", "meaning": "quá", "example": "太好了！(Tài hǎo le!)", "tip": "Chữ Đại (大 - to) thêm một dấu chấm ở dưới để nhấn mạnh sự Thái quá, vượt bậc." },
    { "id": 106, "word": "天气", "pinyin": "tiānqì", "meaning": "thời tiết", "example": "今天天气很好 (Jīntiān tiānqì hěn hǎo)", "tip": "Thiên (Trời), Khí (Không khí). Khí hậu của ông trời." },
    { "id": 107, "word": "听", "pinyin": "tīng", "meaning": "nghe", "example": "听音乐 (Tīng yīnyuè)", "tip": "Chữ Thính. Dùng Miệng (Khẩu - 口) kết hợp cái búa để gõ tạo âm thanh cho tai nghe." },
    { "id": 108, "word": "同学", "pinyin": "tóngxué", "meaning": "bạn học", "example": "同学们好！(Tóngxué men hǎo!)", "tip": "Đồng Học. Những người cùng (Đồng - 同) học chung." },
    { "id": 109, "word": "喂", "pinyin": "wèi", "meaning": "a lô", "example": "喂，你好 (Wèi, nǐ hǎo)", "tip": "Có bộ Khẩu (口) bên trái vì dùng miệng gọi điện thoại 'Alo'." },
    { "id": 110, "word": "我", "pinyin": "wǒ", "meaning": "tôi", "example": "我是越南人 (Wǒ shì Yuènán rén)", "tip": "Hình ảnh hai tay đang cầm binh khí bảo vệ bản thân (cái Tôi)." },
    { "id": 111, "word": "我们", "pinyin": "wǒmen", "meaning": "chúng tôi, chúng ta", "example": "我们是好朋友 (Wǒmen shì hǎo péngyou)", "tip": "Chữ Men (们) có bộ Nhân đứng, là hậu tố số nhiều cho người." },
    { "id": 112, "word": "五", "pinyin": "wǔ", "meaning": "số 5", "example": "五年 (Wǔ nián)", "tip": "Các nét gạch giao nhau tạo thành hình cân bằng." },
    { "id": 113, "word": "喜欢", "pinyin": "xǐhuan", "meaning": "thích", "example": "我喜欢看书 (Wǒ xǐhuan kàn shū)", "tip": "Hỉ Hoan. Hỉ (喜) có chữ Thập và Khẩu -> Mười cái miệng cùng cười vui vẻ." },
    { "id": 114, "word": "下", "pinyin": "xià", "meaning": "dưới, xuống", "example": "桌子下 (Zhuōzi xià)", "tip": "Mũi tên chỉ hướng xuống dưới đường gạch ngang." },
    { "id": 115, "word": "下午", "pinyin": "xiàwǔ", "meaning": "buổi chiều", "example": "今天下午 (Jīntiān xiàwǔ)", "tip": "Hạ Ngọ. Nửa buổi sau giờ Ngọ (12h)." },
    { "id": 116, "word": "下雨", "pinyin": "xiàyǔ", "meaning": "mưa", "example": "下雨了 (Xiàyǔ le)", "tip": "Chữ Vũ (雨) chứa 4 nét chấm giống hệt những giọt mưa đang rơi từ đám mây trên trời xuống (Hạ - 下)." },
    { "id": 117, "word": "先生", "pinyin": "xiānsheng", "meaning": "ông, ngài", "example": "王先生 (Wáng xiānsheng)", "tip": "Tiên (先 - trước) Sinh (生 - đẻ). Người sinh ra trước, ý chỉ bậc tiền bối, tôn xưng nam giới." },
    { "id": 118, "word": "现在", "pinyin": "xiànzài", "meaning": "bây giờ", "example": "现在几点？(Xiànzài jǐ diǎn?)", "tip": "Hiện Tại. Thời điểm xuất hiện ngay lúc này." },
    { "id": 119, "word": "想", "pinyin": "xiǎng", "meaning": "nhớ, muốn, nghĩ", "example": "我想去北京 (Wǒ xiǎng qù Běijīng)", "tip": "Có bộ Tâm (心 - trái tim) ở dưới, Tướng (相) ở trên. Suy nghĩ và mong muốn nằm trong lòng." },
    { "id": 120, "word": "小", "pinyin": "xiǎo", "meaning": "nhỏ, bé", "example": "小猫 (Xiǎo māo)", "tip": "Một nét sổ ở giữa, hai nét phẩy hai bên, tượng trưng cho những hạt bụi nhỏ xíu phân tán." },
    { "id": 121, "word": "小姐", "pinyin": "xiǎojiě", "meaning": "cô", "example": "李小姐 (Lǐ xiǎojiě)", "tip": "Tiểu Thư. Chữ Thư (姐 - chị gái) có bộ Nữ (女) bên trái. Gọi lịch sự phụ nữ trẻ chưa chồng." },
    { "id": 122, "word": "些", "pinyin": "xiē", "meaning": "vài, những (lượng từ)", "example": "一些人 (Yì xiē rén)", "isMeasureWord": true, "tip": "Chữ Thử (此 - này) và chữ Nhị (二 - hai). Một hai cái này (chỉ số lượng vài, một ít)." },
    { "id": 123, "word": "写", "pinyin": "xiě", "meaning": "viết", "example": "写字 (Xiě zì)", "tip": "Có bộ Mịch (冖- che đậy). Viết lách là giữ bí mật giấu đi." },
    { "id": 124, "word": "谢谢", "pinyin": "xièxie", "meaning": "cảm ơn", "example": "谢谢你 (Xièxie nǐ)", "tip": "Tạ Tạ. Bộ Ngôn (讠) bên trái vì Cảm ơn phải nói ra bằng lời." },
    { "id": 125, "word": "星期", "pinyin": "xīngqī", "meaning": "tuần, thứ", "example": "星期一 (Xīngqī yī) - Thứ hai", "tip": "Tinh Kỳ. Tinh (ngôi sao) - có bộ Nhật (mặt trời) và chữ Sinh. Người xưa chu kỳ một tuần theo các vì sao." },
    { "id": 126, "word": "学生", "pinyin": "xuéshēng", "meaning": "học sinh", "example": "我是学生 (Wǒ shì xuéshēng)", "tip": "Học Sinh. Người sinh ra đang trong độ tuổi phải học tập." },
    { "id": 127, "word": "学习", "pinyin": "xuéxí", "meaning": "học tập", "example": "学习汉语 (Xuéxí Hànyǔ)", "tip": "Học Tập. Tập (习) giống hình đôi cánh chim đang tập vỗ cánh bay." },
    { "id": 128, "word": "学校", "pinyin": "xuéxiào", "meaning": "trường học", "example": "去学校 (Qù xuéxiào)", "tip": "Học Hiệu. Hiệu (校) có bộ Mộc (cây), xưa trường học thường dựng bằng gỗ." },
    { "id": 129, "word": "一", "pinyin": "yī", "meaning": "số 1", "example": "一个人 (Yí gè rén)", "tip": "Chỉ một vạch ngang duy nhất là số 1." },
    { "id": 130, "word": "衣服", "pinyin": "yīfu", "meaning": "quần áo", "example": "买衣服 (Mǎi yīfu)", "tip": "Y Phục. Chữ Y (衣) tự nó đã mang hình dáng cổ áo và tà áo vắt chéo." },
    { "id": 131, "word": "医生", "pinyin": "yīshēng", "meaning": "bác sĩ", "example": "他是医生 (Tā shì yīshēng)", "tip": "Y Sinh. Người hành nghề y cứu sống (sinh) người." },
    { "id": 132, "word": "医院", "pinyin": "yīyuàn", "meaning": "bệnh viện", "example": "去医院 (Qù yīyuàn)", "tip": "Y Viện. Viện (院) là cơ sở, tòa nhà lớn làm nơi chữa bệnh." },
    { "id": 133, "word": "椅子", "pinyin": "yǐzi", "meaning": "cái ghế", "example": "一把椅子 (Yì bǎ yǐzi)", "tip": "Kỷ Tử. Kỷ (椅) có bộ Mộc (木 - gỗ) vì ghế ngày xưa được đóng bằng gỗ." },
    { "id": 134, "word": "有", "pinyin": "yǒu", "meaning": "có", "example": "我有一本书 (Wǒ yǒu yì běn shū)", "tip": "Có chữ Nguyệt (mặt trăng/thịt) ở dưới. Có thịt (đồ ăn) trong nhà là 'có'." },
    { "id": 135, "word": "月", "pinyin": "yuè", "meaning": "tháng, mặt trăng", "example": "八月 (Bā yuè)", "tip": "Hình vẽ tượng hình của vầng trăng khuyết." },
    { "id": 136, "word": "在", "pinyin": "zài", "meaning": "ở, đang", "example": "我在家 (Wǒ zài jiā)", "tip": "Bên trong có chữ Thổ (đất). Tồn 'Tại' và sống ở trên mặt đất." },
    { "id": 137, "word": "再见", "pinyin": "zàijiàn", "meaning": "tạm biệt", "example": "再见！(Zàijiàn!)", "tip": "Tái (再 - lại) Kiến (见 - gặp). Nghĩa là Hẹn gặp lại." },
    { "id": 138, "word": "怎么", "pinyin": "zěnme", "meaning": "như thế nào", "example": "怎么去？(Zěnme qù?)", "tip": "Chữ Chẩm (怎) có bộ Tâm (心) ở dưới. Hỏi xem người ta nghĩ thế nào trong lòng." },
    { "id": 139, "word": "怎么样", "pinyin": "zěnmeyàng", "meaning": "như thế nào (hỏi ý kiến)", "example": "这本词典怎么样？(Zhè běn cídiǎn zěnmeyàng?)", "tip": "Thêm chữ Dạng (样 - hình dáng) để hỏi về trạng thái, tình hình." },
    { "id": 140, "word": "这", "pinyin": "zhè", "meaning": "này, đây", "example": "这是我的书 (Zhè shì wǒ de shū)", "tip": "Bộ Xước (辶- bước đi) bao ngoài, bước đến gần để chỉ vật ở ngay 'ĐÂY'." },
    { "id": 141, "word": "中国", "pinyin": "Zhōngguó", "meaning": "Trung Quốc", "example": "我去中国 (Wǒ qù Zhōngguó)", "tip": "Quốc gia (国 - trong có Ngọc bao bởi khung) nằm ở vị trí trung tâm (中)." },
    { "id": 142, "word": "中午", "pinyin": "zhōngwǔ", "meaning": "buổi trưa", "example": "今天中午 (Jīntiān zhōngwǔ)", "tip": "Trung Ngọ. Chính giữa giờ Ngọ (12h trưa)." },
    { "id": 143, "word": "住", "pinyin": "zhù", "meaning": "sống, ở", "example": "我住在北京 (Wǒ zhù zài Běijīng)", "tip": "Bộ Nhân đứng (亻) và chữ Chủ (主). Người làm chủ một nơi thì Sống ở đó." },
    { "id": 144, "word": "桌子", "pinyin": "zhuōzi", "meaning": "cái bàn", "example": "在桌子上 (Zài zhuōzi shàng)", "tip": "Trác Tử. Chữ Trác (桌) ở dưới có chữ Mộc (木) vì bàn thường làm bằng gỗ." },
    { "id": 145, "word": "字", "pinyin": "zì", "meaning": "chữ", "example": "汉字 (Hànzì) - Chữ Hán", "tip": "Bộ Miên (宀 - mái nhà) và Tử (子 - trẻ nhỏ). Trẻ nhỏ được nuôi dạy trong nhà sẽ biết Chữ." },
    { "id": 146, "word": "昨天", "pinyin": "zuótiān", "meaning": "hôm qua", "example": "昨天我去学校了 (Zuótiān wǒ qù xuéxiào le)", "tip": "Tạc Thiên. Chữ Tạc (昨) có bộ Nhật (ngày) chỉ khoảng thời gian đã qua." },
    { "id": 147, "word": "坐", "pinyin": "zuò", "meaning": "ngồi", "example": "请坐 (Qǐng zuò) - Mời ngồi", "tip": "Hình ảnh hai người (hai bộ nhân 人) đang ngồi đối diện nhau trên mặt đất (Thổ - 土)." },
    { "id": 148, "word": "做", "pinyin": "zuò", "meaning": "làm", "example": "你在做什么？(Nǐ zài zuò shénme?)", "tip": "Có bộ Nhân (亻) và chữ Cố (故). Con người dùng sức để hoàn thành việc (Làm việc)." }
];